### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by chris-griffin** [debops/ansible-unattended_upgrades#19]
![image](https://user-images.githubusercontent.com/1795659/34697114-a356d08a-f49f-11e7-9cfb-8de31547c471.png)

**Comment by drybjed** [comment]
Thanks for the heads up. I made a redirect to the new documentation location for all of the roles, it should work now.

Keep in mind that the documentation is for the roles present in the [DebOps monorepo](https://github.com/debops/debops/) and not the roles in separate repositories. They haven't diverged much yet, though.

**Comment by chris-griffin** [comment]
Thanks @drybjed
