### ISSUE TITLE
unattended_upgrades__default_blacklist blacklists vim and libc6?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-unattended_upgrades#5]
I assume this was meant to be an example as upstream also uses them as example or is there a good reason to blacklist them? Remember, `libc` sometimes also has vulnerabilities :wink:

**Comment by drybjed** [comment]
If a system automatically upgrades `libc`, and it breaks in the middle of the night, you will be blamed. With a blacklist, I imagine that you can get an email about pending upgrade and plan for it accordingly, test if everything works, etc. The same with `vim`, although removing that is probably a good idea - there's always `ed` if your preferred editor breaks.

**Comment by ypid** [comment]
@drybjed Did you have problems with breaking `libc` before? Would you recommend that people who deploy Debian systems in customer networks and then might have no easy access to them afterwards (and basically no one carrying for the systems) also auto upgrade `libc`? (I would go for that because it breaking is better than having a vulnerability in case system admins otherwise are responsible for the system). Also, I did not yet have the problem of something breaking by such a update.

OK, I removed `vim` for an upcoming PR.

**Comment by drybjed** [comment]
No, I haven't had an issue with `libc` upgrade breaking systems. I suppose we could remove it from the defaults as well. I wonder if setting up local APT repository for tiered upgrades could be a good solution for making sure nothing breaks in a staging environment before pushing the updates to production.

**Comment by ypid** [comment]
@drybjed All right. In this case removing `libc` from the blacklist is a good idea I think. Tiered upgrades should be used to test upgrades before pushing to production. (I have no experience with that yet).
